platform: x64

image: Visual Studio 2017

configuration: Release

environment: Qt5_DIR: C:\Qt\5.13.0\msvc2017_64

before_build:
        - mkdir "build"
        - cd "build"
        - cmake .. -G "Visual Studio 2015 Win64"

build:
        project: build\ALL_BUILD.vcxproj
        verbosity: minimal

artifacts:
        - path: build/herald-w64.zip
          name: Herald
